version: "3.4"

services:
  udp2ros:
    image: gst-ros-bridge:ros2
    networks:
      ipcnet:
        ipv4_address: 172.33.100.2
    ports:
      - "7001:7001/udp"
    environment:
      - GST_PLUGIN_PATH=install/gst_bridge/lib/gst_bridge
    command: >
      bash -c '
      source install/setup.bash && gst-launch-1.0 udpsrc port=7001 caps="application/x-rtp"  ! rtpjpegdepay ! jpegdec ! videoconvert! rosimagesink ros-topic=/image_proc_chain/io/image_in
      '

  ipc:
    image: ipc:humble
    networks:
      ipcnet:
        ipv4_address: 172.33.100.3
    command: >
      ros2 launch image_proc_chain image_proc_chain.launch.py

  rosbridge:
    image: rosbridge:humble
    networks:
      ipcnet:
        ipv4_address: 172.33.100.4
    ports:
      - "9090:9090/tcp"
    command: >
      ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  wvs:
    image: web_video_server:humble
    networks:
      ipcnet:
        ipv4_address: 172.33.100.5
    ports:
      - "9091:8080/tcp"
    command: >
      ros2 run web_video_server web_video_server

  test1:
    image: ipc:humble
    networks:
      ipcnet:
        ipv4_address: 172.33.100.100
    command: >
      ros2 topic echo --once /image_proc_chain/io/image_out

  test2:
    image: ipc:humble
    networks:
      ipcnet:
        ipv4_address: 172.33.100.101
    command: >
      ros2 topic pub /my_topic std_msgs/String "data: 'Hello world!'" -r 1


networks:
  ipcnet:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.33.100.0/24
          gateway: 172.33.100.1
